framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            'Symfony\Component\Mercure\Update': amqp
            # does not work anymore with the next line...
            #'App\Entity\Queue': amqp

