framework:
    workflows:
        queue:
            type: 'state_machine'
            audit_trail:
                enabled: true
            supports:
                - App\Entity\WaitingLine
            initial_place: started
            places:
                - started
                - waiting
                - ready
            transitions:
                wait:
                    from: started
                    to: waiting
                ready:
                    from: waiting
                    to: ready
                reset:
                    from: [waiting, ready]
                    to: started
